version: '3.6'
services:
  gitlab-runner:
    image: 'gitlab/gitlab-runner:latest'
    restart: always
    container_name: gitlab-runner
    environment:
      - TZ=Asia/Beijing
    volumes:
      - '$HOME/gitlab-runner/config:/etc/gitlab-runner' # On macOS, use /Users/Shared instead of /srv.
      - '/var/run/docker.sock:/var/run/docker.sock'
      # - './config:/etc/gitlab-runner'